# Generated by Django 3.0.7 on 2020-06-20 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('telephone', models.IntegerField(max_length=10)),
                ('cv', models.FileField(max_length=200, upload_to='')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_poste', models.CharField(max_length=200)),
                ('lieu_poste', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Poste_Candidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutement.Candidat')),
                ('id_poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutement.Poste')),
            ],
        ),
    ]
