# Generated by Django 3.0.7 on 2020-06-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
